name: Deploy ML Model to Hugging Face

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PR to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can choose a specific version if needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Deploy to Hugging Face using huggingface_hub
      - name: Deploy model to Hugging Face
        run: |
          python -m pip install huggingface_hub

          # Set the Hugging Face token
          hf_token="${{ secrets.huggingtoken }}"

          # Log in to Hugging Face (this authenticates your token)
          python -c "from huggingface_hub import login; login(token='${hf_token}')"

          # Push the model to Hugging Face Space 'firstspace'
          python -c "from huggingface_hub import upload_folder; upload_folder(
              repo_id='hassan30khawaja/firstspace',  # Use your Hugging Face Space name here
              folder_path='./',  # Path to your model files
              token='${hf_token}'  # Hugging Face token for auth
